### ISSUE TITLE
Timestamp ofTimeMicroseconds(long microseconds) fails for epoch dates with microseconds

### ISSUE THREAD

**Issue by gmreddy278** [googleapis/java-core#136]
com.google.cloud.Timestamp.ofTimeMicroseconds(long microseconds) fails with IllegalArgumentException if the given date is epoch and not truncated to seconds, in the concrete example, -8499613106649 epoch timestamp was used.

google-cloud-core version: 1.62.0

Stacktrace fragment:

java.lang.IllegalArgumentException: timestamp out of range: -8499613106649, 749440000
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:357)
	at com.google.cloud.Timestamp.ofTimeMicroseconds(Timestamp.java:96)

**Comment by athakor** [comment]
@gmreddy278 as you can see [here](https://github.com/googleapis/java-core/blob/master/google-cloud-core/src/main/java/com/google/cloud/Timestamp.java#L87) method `com.google.cloud.Timestamp.ofTimeMicroseconds(long microseconds)` itself accept the `long` value instead of `integer` so you must have to pass `long` instead of `integer.`

FYI, If there is no `suffix`, and it is an `integral` type `(e.g. -8499613106649),` then you need to cast as there is no specific `suffix`.

The Java spec allows both upper and lower case suffixes, but the upper case version for longs is preferred, as the upper case `L` is less easy to confuse with a numeral `1` than the lower case` l`.
